/**
 * A national, first-party census of LOCAL GOVERNMENT fiscal calendars, built
 * from the Federal Audit Clearinghouse.
 *
 * ⚠ NO SHEBANG. This is a library, never executed — and `tests/waSao.test.mjs`
 * fails the build if any module a test imports starts with `#!`.
 *
 * ── What this is ────────────────────────────────────────────────────────────
 * Every government expending >= $750k of federal awards files a Single Audit,
 * and the FAC publishes the AUDITED PERIOD of that filing — the auditee's own
 * submission, made under federal penalty. Censusing it answers "what calendar
 * does this government run" for the whole country at once, instead of one
 * charter or ACFR at a time.
 *
 * `docs/fac/fac-local-fiscal-year-ends.csv` covers **audit years 1998-2026**
 * across **56 jurisdictions**, and is regenerated by
 * `scripts/buildFacFiscalYearCensus.mjs` from two free bulk downloads (no API
 * key, no rate limit). See that file for the download URLs and every filter.
 *
 * ── Why a state's "usual" month is never an entity's month ──────────────────
 * This census exists because the generalisation keeps being wrong, and the
 * national measurements show how badly:
 *
 *   • MICHIGAN municipalities are modally JULY — but Michigan TOWNSHIPS are
 *     APRIL, and 55 Michigan municipalities run MARCH.
 *   • ILLINOIS municipalities are modally MAY. Illinois COUNTIES are DECEMBER.
 *   • UTAH counties are JANUARY while Utah cities are JULY.
 *   • TEXAS locals are modally OCTOBER — but HOUSTON is July, EL PASO is
 *     September, 42 counties are January, and HARRIS COUNTY ran MARCH until it
 *     switched to October in 2023.
 *   • NEW YORK villages are largely JUNE while its cities and counties are
 *     JANUARY.
 *   • CALIFORNIA cities are July with five October exceptions, two of which are
 *     general-law cities that the old charter-city framing could never have
 *     found.
 *
 * ⚠⚠ SO A STATE-WIDE MONTH IS A DEFAULT, NEVER A FACT ABOUT AN ENTITY.
 * `dominantMonthFor()` is MEASURED per (state, kind) rather than declared, and
 * `censusMonthFor()` — the per-entity fact — is what a loader must consult.
 *
 * ── What a census CANNOT tell you ───────────────────────────────────────────
 *   (a) It begins at audit year 1998. A change made earlier is invisible.
 *       Every TT row is FY2003 or later, so the window covers our data.
 *   (b) An entity below the $750k federal threshold NEVER FILES, so absence is
 *       not evidence of anything. Nationally that is most small towns.
 *   (c) A period's END does not reveal its LENGTH. In a changeover year the
 *       audit covers a SHORT stub that still begins in the OLD month, so the
 *       month inferred from the end is wrong in exactly that year — see
 *       `changeoverYears()`, and the `other`/`biennial` rows which record a
 *       stub's length where the federal record states it.
 */

import fs from 'node:fs';
import path from 'node:path';

const HERE = path.dirname(new URL(import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1'));
const REPO = path.resolve(HERE, '..', '..');

/** The single national evidence file. */
export const EVIDENCE_CSV = path.join(REPO, 'docs', 'fac', 'fac-local-fiscal-year-ends.csv');

/**
 * ⚠ 1998 ONLY BECAUSE THE HISTORIC HALF IS LOADED. The FAC publishes 2016+ and
 * 1998-2015 as two separate downloads with different schemas; a census built
 * from the modern file alone starts at 2016, which was this census's blind spot
 * while TT held rows back to FY2003.
 */
export const WINDOW = { firstAuditYear: 1998, lastAuditYear: 2026 };

/** Measured when the national census was built. A move here means the federal record moved. */
export const BASELINE = { rows: 17921, entities: 16091, jurisdictions: 52, exceptions: 1281 };

/**
 * Spot baselines for the states TT actually holds data in, so a silent change in
 * one state cannot hide inside a national total.
 */
export const STATE_BASELINE = {
  CA: { entities: 537, exceptions: 5, dominant: { municipality: 7 } },
  MN: { entities: 658, exceptions: 0, dominant: { municipality: 1, county: 1, township: 1 } },
  MA: { entities: 362, exceptions: 0, dominant: { municipality: 7, county: 7 } },
  OH: { entities: 565, exceptions: 1, dominant: { municipality: 1, county: 1, township: 1 } },
  TX: { entities: 865, exceptions: 86, dominant: { municipality: 10, county: 10 } },
  UT: { entities: 182, exceptions: 0, dominant: { municipality: 7, county: 1 } },
  WA: { entities: 296, exceptions: 0, dominant: { municipality: 1, county: 1 } },
  MD: { entities: 109, exceptions: 0, dominant: { municipality: 7, county: 7 } },
};

const HEADER = 'state,entity,kind,period,start_month,number_months,audit_years';

/** `"1998-2000 2002"` -> `[1998,1999,2000,2002]`. */
export function expandYears(text) {
  const out = [];
  for (const part of String(text ?? '').trim().split(/\s+/).filter(Boolean)) {
    const m = /^(\d{4})-(\d{4})$/.exec(part);
    if (m) { for (let y = Number(m[1]); y <= Number(m[2]); y += 1) out.push(y); } else out.push(Number(part));
  }
  return out;
}

let ALL = null;
/** Parse the national evidence once. Deliberately strict — a malformed row throws. */
export function readEvidence(stateCode) {
  if (ALL === null) {
    const text = fs.readFileSync(EVIDENCE_CSV, 'utf8');
    const lines = text.split(/\r?\n/).filter((l) => l.trim() !== '');
    const header = lines.shift();
    if (header !== HEADER) throw new Error(`unexpected header in ${EVIDENCE_CSV}: ${header}`);
    ALL = lines.map((line, i) => {
      const [state, entity, kind, period, startMonth, months, years] = line.split(',');
      if (!state || !entity || !kind || !period) {
        throw new Error(`malformed record at line ${i + 2} of ${EVIDENCE_CSV}: ${line}`);
      }
      return {
        state, entity, kind, period,
        startMonth: startMonth === '' ? null : Number(startMonth),
        months: months === '' ? null : Number(months),
        years: expandYears(years),
      };
    });
  }
  if (stateCode === undefined) return ALL;
  if (!ALL.some((r) => r.state === stateCode)) throw new Error(`no census records for ${stateCode}`);
  return ALL.filter((r) => r.state === stateCode);
}

/** Every jurisdiction the census covers. */
export function states() {
  return [...new Set(readEvidence().map((r) => r.state))].sort();
}

const CENSUS_CACHE = new Map();
/**
 * entity -> { kind, byMonth: Map(startMonth -> [auditYears]) } for one state.
 *
 * ⚠ Cached. `censusGuard` is called once per entity per fiscal year by a loader,
 * and verifying TT's 38,801 California rows against an unmemoised census did not
 * finish in two minutes.
 */
export function buildCensus(stateCode) {
  if (!CENSUS_CACHE.has(stateCode)) {
    const census = new Map();
    for (const r of readEvidence(stateCode)) {
      if (r.period !== 'annual' || r.startMonth === null) continue;
      const entry = census.get(r.entity) ?? { name: r.entity, kind: r.kind, byMonth: new Map() };
      entry.byMonth.set(r.startMonth, [...(entry.byMonth.get(r.startMonth) ?? []), ...r.years].sort());
      census.set(r.entity, entry);
    }
    CENSUS_CACHE.set(stateCode, census);
  }
  return CENSUS_CACHE.get(stateCode);
}

/** The non-annual periods — a stub's length is the clearest evidence of a change. */
export function stubPeriods(stateCode) {
  return readEvidence(stateCode).filter((r) => r.period !== 'annual');
}

/**
 * The MEASURED modal start month for one (state, kind), counting entities.
 *
 * ⚠ Per KIND, not per state. Michigan townships are April while its
 * municipalities are July; Illinois counties are December while its
 * municipalities are May. A single per-state month would call thousands of
 * correct governments exceptional and hide the real outliers among them.
 */
export function dominantMonthFor(stateCode, kind) {
  const counts = new Map();
  for (const e of buildCensus(stateCode).values()) {
    if (e.kind !== kind) continue;
    const [month] = [...e.byMonth.entries()].sort((a, b) => b[1].length - a[1].length)[0] ?? [];
    if (month) counts.set(month, (counts.get(month) ?? 0) + 1);
  }
  const best = [...counts.entries()].sort((a, b) => b[1] - a[1])[0];
  return best ? best[0] : null;
}

/**
 * The audit years in which an entity's start month differs from the year before.
 *
 * ⚠⚠ THE CENSUS IS BLIND IN EXACTLY THIS YEAR. A changeover produces a SHORT
 * period whose END is on the new calendar but whose START is still the old one
 * (Huntington Beach's was nine months, Oct 1 2017 - Jun 30 2018). A period's end
 * does not tell you its length, so a changeover year must be settled from a
 * document, never from this census.
 */
export function changeoverYears(entry) {
  const byYear = new Map();
  for (const [month, years] of entry.byMonth) for (const y of years) byYear.set(y, month);
  const years = [...byYear.keys()].sort((a, b) => a - b);
  const out = [];
  for (let i = 1; i < years.length; i += 1) {
    if (byYear.get(years[i]) !== byYear.get(years[i - 1])) out.push(years[i]);
  }
  return out;
}

/**
 * A month seen in exactly ONE audit year, beside a month seen in several, is a
 * transcription artefact rather than a calendar — Torrance's stray `2020-07-01`,
 * Delano's lone `2008-12-31`, Seaside's lone `2001-09-30`. Real calendars and
 * real changeovers both persist.
 */
function realMonths(entry) {
  const months = [...entry.byMonth.entries()]
    .map(([month, years]) => ({ month, years }))
    .sort((a, b) => b.years.length - a.years.length);
  if (months.length < 2) return { real: months, stray: [] };
  const real = months.filter((m) => m.years.length > 1);
  if (real.length === 0) return { real: months.slice(0, 1), stray: months.slice(1) };
  return { real, stray: months.filter((m) => !real.includes(m)) };
}

/** Every entity whose calendar is not its (state, kind) modal month. */
export function exceptions(stateCode) {
  const out = [];
  const dominant = new Map();
  for (const entry of buildCensus(stateCode).values()) {
    if (!dominant.has(entry.kind)) dominant.set(entry.kind, dominantMonthFor(stateCode, entry.kind));
    const { real, stray } = realMonths(entry);
    // ⚠ ONE FILING IS NOT A CALENDAR, and the count must be over the REAL months
    // — an entity with two records in two different months has every month
    // looking like a stray, and counting all its years would smuggle it in.
    // This is where the residual noise sits: a government whose whole filing
    // history is mailed from the next state (Skagway AK filed under WA, Newark
    // DE under MD) and one-off transcription errors (Delano's lone 2008-12-31).
    if (real.reduce((n, m) => n + m.years.length, 0) < 2) continue;
    if (real.every((m) => m.month === dominant.get(entry.kind))) continue;
    out.push({
      state: stateCode,
      name: entry.name,
      kind: entry.kind,
      months: real.map((m) => ({ month: m.month, years: m.years })),
      strayYears: stray.flatMap((m) => m.years),
      changed: real.length > 1,
      changeoverYears: changeoverYears(entry),
    });
  }
  return out.sort((a, b) => a.name.localeCompare(b.name));
}

/**
 * What the census says one entity's fiscal year starts in, for one fiscal year.
 *
 * Returns `{ month, auditYears }`, or `{ unknown: reason }`. ⚠ `unknown` IS NOT
 * A LICENCE TO APPLY THE STATE DEFAULT — it means nobody has evidence, which is
 * exactly when a loader should refuse rather than guess.
 */
export function censusMonthFor(stateCode, entityName, fiscalYear) {
  let census;
  try { census = buildCensus(stateCode); } catch { return { unknown: `no census for ${stateCode}` }; }
  const entry = census.get(entityName);
  if (!entry) {
    return { unknown: `${entityName}, ${stateCode} filed no Single Audit in ${WINDOW.firstAuditYear}-`
      + `${WINDOW.lastAuditYear} (or spends under the $750k federal threshold). Absence is not `
      + 'evidence of the state\'s usual month — read a document.' };
  }
  const { real } = realMonths(entry);
  if (fiscalYear === undefined || fiscalYear === null) {
    if (real.length > 1) {
      return { unknown: `${entityName}, ${stateCode} CHANGED its fiscal year `
        + `(${real.map((m) => `month ${m.month} in ${m.years.join('/')}`).join('; ')}) — `
        + 'a month cannot be resolved without a fiscal year' };
    }
    return { month: real[0].month, auditYears: real[0].years };
  }
  const fy = Number(fiscalYear);
  if (!Number.isInteger(fy)) return { unknown: `unparseable fiscal year ${JSON.stringify(fiscalYear)}` };
  if (changeoverYears(entry).includes(fy)) {
    return { unknown: `FY${fy} is ${entityName}'s CHANGEOVER year: the audited period ends on the `
      + 'new calendar but begins on the old one, and its length is not recorded here. '
      + 'Read the entity\'s own statements for that year.' };
  }
  for (const m of real) if (m.years.includes(fy)) return { month: m.month, auditYears: m.years };
  return { unknown: `FY${fy} is outside the audited years for ${entityName} `
    + `(observed ${real.map((m) => `month ${m.month}: ${m.years[0]}-${m.years[m.years.length - 1]}`).join('; ')}). `
    + 'This census does not extrapolate.' };
}

/**
 * The guard a loader should call before writing a fiscal-year start month.
 *
 * `{ ok: true }` when the census has no evidence — silence is not disagreement —
 * and `{ error }` when the month about to be written CONTRADICTS the entity's own
 * federally filed audit.
 *
 * ⚠ This exists because a loader takes ONE month for a whole multi-entity run.
 * Loading Texas with `10` is right for 718 of 842 entities and WRONG for Houston,
 * El Paso and 42 January counties — and nothing would fail, because this column
 * moves no dollar and every tie test would still pass at $0.
 */
export function censusGuard(entityName, stateCode, month, fiscalYear) {
  if (month === undefined || month === null) return { ok: true };
  const seen = censusMonthFor(stateCode, entityName, fiscalYear);
  if (seen.unknown) return { ok: true, unknown: seen.unknown };
  if (Number(month) === seen.month) return { ok: true, month: seen.month };
  return {
    error: `month ${month} contradicts the federal audit record for ${entityName}, ${stateCode}`
      + `${fiscalYear ? ` in FY${fiscalYear}` : ''}: its own Single Audit filings for `
      + `${seen.auditYears[0]}-${seen.auditYears[seen.auditYears.length - 1]} report a fiscal year `
      + `starting in month ${seen.month}. See ${path.relative(REPO, EVIDENCE_CSV)}. `
      + 'Correct the month, restrict the run, or — if the census is wrong — say why in the '
      + "entity's registry entry.",
  };
}
