-- Detect cities TT holds as TWO entities because a publisher renamed them.
--
--   psql "$DATABASE_URL" -f scripts/detectForkedEntities.sql
--   (or paste into the Supabase SQL editor / run through the Supabase MCP)
--
-- Expect ZERO rows. Any row is a candidate fork to adjudicate by hand — this
-- finds candidates, it does not merge anything.
--
-- ── WHY THIS EXISTS ────────────────────────────────────────────────────────
--
-- The loaders match entities BY NAME. When a publisher changes the name it
-- prints, the match fails and a SECOND entity is created; every year from that
-- point forward lands on the new row and the city's history is severed. It has
-- happened twice, both from the Minnesota Office of the State Auditor:
--
--   2026-09-14  Marine on Saint Croix / Marine On Saint Croix   "on" -> "On"
--   2026-09-15  Birchwood            / Birchwood Village        a word added
--
-- ⚠⚠ NEITHER WAS FOUND BY LOOKING. Marine surfaced because both halves claimed
-- the same geoid and the backfill's uniqueness check refused it; Birchwood
-- surfaced while chasing an unrelated one-row discrepancy. Nothing fails when a
-- city forks: both halves carry honest data, every total ties, and EACH HALF
-- LOOKS COMPLETE. Only a reader who knows the missing years exist can tell.
--
-- ⚠ Making the match case-insensitive (#182) closes the Marine shape and NOT
-- the Birchwood shape: "on" -> "On" is a case change, "Birchwood" ->
-- "Birchwood Village" is a whole added word. The durable fix is matching on a
-- stable key rather than the published name. Until then, run this.
--
-- ── THE SIGNATURE ──────────────────────────────────────────────────────────
--
-- Both known forks shared all five, and a genuine pair of governments will not:
--
--   1. same state
--   2. ONE shared publisher — both halves carry the same single data_source
--   3. year ranges that DO NOT OVERLAP and sit adjacent (gap of 0 or 1)
--   4. related names after normalisation (accents folded, punctuation dropped,
--      leading/trailing designators stripped, or trigram-similar)
--   5. populations within 25% — different vintages of one small town, not two
--      different places
--
-- Plus two guards against the obvious false positives:
--
--   same entity_type    "Napa" (city) and "Napa County" (county) normalise to
--                       the same core once "County" is stripped. They are not a
--                       fork. Without this guard that pattern floods the output.
--   geoid agreement     two rows with DIFFERENT non-null geoids are two
--                       different governments, full stop.
--
-- ⚠ VALIDATED, NOT ASSUMED. Both known forks are already merged, so an empty
-- result proves nothing on its own. This query was checked by REBUILDING the
-- Birchwood fork inside a rolled-back transaction: it returned exactly that one
-- pair, gap 0, name similarity 1.00. An empty result is only meaningful because
-- the detector is known to fire.
--
-- ⚠ It cannot see a fork where the two halves' years OVERLAP (a re-load under a
-- new name rather than a clean handover), nor one whose names are unrelated
-- (a genuine renaming, e.g. a town incorporating under a new name).

-- ⚠ THE RULE ITSELF NOW LIVES IN treasury.detect_forked_entities(), so that
-- this file and the loaders that call it cannot drift. Migration
-- 20260916092000_detect_forked_entities_fn.sql. The loaders reach it through
-- assertNoNewForks() in scripts/lib/ensureMunicipality.mjs.
--
-- ⚠⚠ An INSERT-time version of this check was measured and abandoned: ten
-- existing pairs tripped its name-and-population rule and ALL TEN were
-- distinct governments (Bell/Bell Gardens, Avon/Avon Lake, ...). Three of the
-- five signals below come from the budgets table, so the rule is only usable
-- AFTER a load has written them.

SELECT * FROM treasury.detect_forked_entities();
