-- Move the treasury sync API key out of a plaintext table and into Vault.
--
-- What was wrong
-- ──────────────
-- The key lived as a plaintext row in `treasury.sync_config`:
--
--   key = 'sync_api_key', value = 'tsyn…'   (38 chars, created 2026-03-27)
--
-- `anon` and `authenticated` both held SELECT on that table. RLS is enabled with
-- ZERO policies, so those grants were dead in practice — verified over HTTP with the
-- anon key against a working control: the REST read returns `[]` and
-- treasury_get_sync_key() 401s for anon. So this was NOT a public leak, and the
-- earlier note claiming "any query returns it in plaintext" overstated it.
--
-- It was still worth rotating:
--   * the value appeared in assistant session transcripts, repeatedly;
--   * the `ev_api` role held full CRUD on the table, so a second application role
--     could read the sync credential for no reason;
--   * a plaintext credential in an ordinary table is one missing RLS policy away
--     from being exactly the leak it was described as.
--
-- What this does
-- ──────────────
-- The replacement key was generated BY POSTGRES, inside the database
-- (`vault.create_secret('tsyn_' || encode(gen_random_bytes(32),'base64'), …)`), so
-- its plaintext has never existed in a transcript, a shell history, a CLI argument
-- or a file on disk. Nobody has seen it — which is the property the old key lost and
-- cannot get back.
--
--   * treasury_get_sync_key() now reads vault.decrypted_secrets. Its grants are
--     unchanged: EXECUTE to postgres and service_role only, never anon.
--   * cron jobs 5 (treasury-daily-sync) and 6 (treasury-weekly-full-sync) read the
--     same Vault secret when building their x-api-key header. Both run as `postgres`,
--     which can decrypt. Neither job ever hardcoded the key — they always read it at
--     runtime — so there is no literal to update, contrary to the earlier note about
--     "re-pointing" them.
--
-- The old row and the stale grants are removed in 20260827000700, after this cutover
-- is verified end to end. Doing it in one step would leave no way to check the new
-- path works while the old one still does.

-- ── treasury_get_sync_key: read Vault, not the plaintext table ──────────────────
CREATE OR REPLACE FUNCTION public.treasury_get_sync_key()
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'treasury', 'public'
AS $function$
DECLARE v text;
BEGIN
  SELECT decrypted_secret INTO v
  FROM vault.decrypted_secrets
  WHERE name = 'treasury_sync_api_key';
  RETURN v;
END;
$function$;

-- ── cron jobs 5 and 6: same header, sourced from Vault ──────────────────────────
SELECT cron.alter_job(
  5,
  command := $cmd$SELECT net.http_post(
    url := 'https://kxsdzaojfaibhuzmclfq.supabase.co/functions/v1/treasury-sync-orchestrator',
    body := '{"triggered_by": "cron"}'::jsonb,
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'x-api-key', (SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name = 'treasury_sync_api_key')
    )
  )$cmd$
);

SELECT cron.alter_job(
  6,
  command := $cmd$SELECT net.http_post(
    url := 'https://kxsdzaojfaibhuzmclfq.supabase.co/functions/v1/treasury-sync-orchestrator',
    body := '{"triggered_by": "cron", "force": true}'::jsonb,
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'x-api-key', (SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name = 'treasury_sync_api_key')
    )
  )$cmd$
);

-- Refuse to leave a job pointing at a secret that does not resolve. A cron job whose
-- header expression silently returns NULL would send no key and 401 every night while
-- reporting nothing — the invisible-failure shape this codebase keeps rediscovering.
DO $$
DECLARE v_len int;
BEGIN
  SELECT length(decrypted_secret) INTO v_len
  FROM vault.decrypted_secrets WHERE name = 'treasury_sync_api_key';
  IF v_len IS NULL OR v_len < 32 THEN
    RAISE EXCEPTION 'vault secret treasury_sync_api_key is missing or too short (length %)', v_len;
  END IF;
  IF (SELECT count(*) FROM cron.job
      WHERE jobid IN (5,6) AND command LIKE '%vault.decrypted_secrets%') <> 2 THEN
    RAISE EXCEPTION 'expected both cron jobs 5 and 6 to read the key from Vault';
  END IF;
  IF (SELECT count(*) FROM cron.job
      WHERE jobid IN (5,6) AND command LIKE '%sync_config%') <> 0 THEN
    RAISE EXCEPTION 'a cron job still reads treasury.sync_config';
  END IF;
END $$;
